In [1]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr[0]+arr[3])

5


In [3]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr[0,2]+arr[2,1])
print(arr[0])


11
[1 2 3]


In [4]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0][1][2])

6


In [6]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr[1,-1])

6


In [22]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr[1:4:2])
print(arr[-3:])

[2 4]
[3 4 5]


In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
