In [1]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[10,11,12],[13,14,15],[16,17,18]])

Sum = np.add(arr1,arr2)
Diff = np.subtract(arr1,arr2)
Mul = np.multiply(arr1,arr2)
Div = np.divide(arr1,arr2)
Trans = np.transpose(arr1)

print("arr1 : ")
print(arr1)

print("\narr2 : ")
print(arr2)

print("\nSum : ")
print(Sum)

print("\nDifference : ")
print(Diff)

print("\nProduct : ")
print(Mul)

print("\nDivision : ")
print(Div)

print("\n Transpose of arr1 : ")
print(Trans)

arr1 : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2 : 
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Sum : 
[[11 13 15]
 [17 19 21]
 [23 25 27]]

Difference : 
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]

Product : 
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]

Division : 
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]

 Transpose of arr1 : 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [4]:
import numpy as np

def myAdd(x,y):
    return x+y

my_add = np.frompyfunc(myAdd,2, 1)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

print(my_add(arr1, arr2))

print(type(my_add))

[7 9 11 13 15]
<class 'numpy.ufunc'>


In [3]:
import numpy as np

arr = np.arange(16).reshape(4,4)

print("Before Swapping :")
print(arr)

print("\nAfter Swapping :\n")
arr[:,[1,3]] = arr[:,[3,1]]

print(arr)

Before Swapping :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

After Swapping :

[[ 0  3  2  1]
 [ 4  7  6  5]
 [ 8 11 10  9]
 [12 15 14 13]]


In [3]:
import numpy as np

base = np.array([10,11,12,13,14])
Power = np.array([2,3,4,5,6])

ans = np.power(base, Power)

print(ans)

[    100    1331   20736  371293 7529536]


In [3]:
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [15]:
import numpy as np

arr = np.array([-2.85, 85.24849])

# arr = np.trunc(arr)
# arr = np.round(arr)
# arr = np.fix(arr)
# arr = np.around(arr,1)
arr = np.ceil(arr)

print(arr)

[-2. 86.]


In [16]:
import numpy as np

a = np.arange(5)
b = np.arange(5)[: ,np.newaxis]

print(a)
print(b)

c = a*b

print(c)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
